"""add source column to invoices

Revision ID: 106f1c63da4b
Revises: b2ccbdc86f48
Create Date: 2026-08-17 13:40:08.024381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '106f1c63da4b'
down_revision: Union[str, Sequence[str], None] = 'b2ccbdc86f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Existing rows all predate Gmail intake -- they're genuinely 'manual_upload', not
    # a placeholder -- so backfill with that as the default, then drop it so the
    # application is the sole source of truth for new rows.
    op.add_column(
        'invoices', sa.Column('source', sa.String(), nullable=False, server_default='manual_upload')
    )
    op.alter_column('invoices', 'source', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'source')
    # ### end Alembic commands ###
