"""add step_timestamps_ms to agent_investigations

Revision ID: 37bcf08acded
Revises: 106f1c63da4b
Create Date: 2026-08-17 14:05:00.256092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37bcf08acded'
down_revision: Union[str, Sequence[str], None] = '106f1c63da4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_investigations', sa.Column('step_timestamps_ms', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_investigations', 'step_timestamps_ms')
    # ### end Alembic commands ###
