"""add po_type to purchase orders

Revision ID: 5f6cecacc466
Revises: 8d33875925f7
Create Date: 2026-08-14 19:28:25.915203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f6cecacc466'
down_revision: Union[str, Sequence[str], None] = '8d33875925f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Existing rows predate po_type -- backfill with a placeholder default (mock data
    # only, immediately re-seeded with correct per-PO types afterward), then drop the
    # default so the application is the sole source of truth for new rows.
    op.add_column(
        'purchase_orders', sa.Column('po_type', sa.String(), nullable=False, server_default='goods')
    )
    op.alter_column('purchase_orders', 'po_type', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'po_type')
    # ### end Alembic commands ###
