"""add V1-V9 validation pipeline fields

Revision ID: 8d33875925f7
Revises: a4b5c19776bc
Create Date: 2026-08-14 19:20:51.708867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d33875925f7'
down_revision: Union[str, Sequence[str], None] = 'a4b5c19776bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing rows predate the numbered validation pipeline -- backfill with a
    # distinct 'LEGACY' marker (never a real PRE/V1-V9 value), then drop the
    # default so the application is the sole source of truth for new rows.
    op.add_column(
        'invoice_validation_issues',
        sa.Column('step', sa.String(), nullable=False, server_default='LEGACY'),
    )
    op.alter_column('invoice_validation_issues', 'step', server_default=None)
    op.add_column('invoices', sa.Column('vendor_country', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('po_number', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('company_code', sa.String(), nullable=True))
    op.add_column('purchase_orders', sa.Column('company_code', sa.String(), nullable=True))
    op.add_column('suppliers', sa.Column('country', sa.String(), nullable=True))
    op.add_column('suppliers', sa.Column('default_tax_rate', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('suppliers', sa.Column('bank_reference', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'bank_reference')
    op.drop_column('suppliers', 'default_tax_rate')
    op.drop_column('suppliers', 'country')
    op.drop_column('purchase_orders', 'company_code')
    op.drop_column('invoices', 'company_code')
    op.drop_column('invoices', 'po_number')
    op.drop_column('invoices', 'vendor_country')
    op.drop_column('invoice_validation_issues', 'step')
    # ### end Alembic commands ###
