"""drop invoice vendor_name/invoice_number unique constraint

Revision ID: b271b87483c1
Revises: 4e734687dad8
Create Date: 2026-08-13 18:35:33.128867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b271b87483c1'
down_revision: Union[str, Sequence[str], None] = '4e734687dad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_invoice_vendor_number'), 'invoices', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_invoice_vendor_number'), 'invoices', ['vendor_name', 'invoice_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
