"""add invoice_decisions table and invoices.decision_status column

Revision ID: c12b8cf23e77
Revises: b271b87483c1
Create Date: 2026-08-13 20:04:40.164724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c12b8cf23e77'
down_revision: Union[str, Sequence[str], None] = 'b271b87483c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('agent_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('agent_recommendation', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('decision_reasoning', sa.Text(), nullable=False),
    sa.Column('policy_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_investigation_id'], ['agent_investigations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('invoices', sa.Column('decision_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'decision_status')
    op.drop_table('invoice_decisions')
    # ### end Alembic commands ###
