"""add termination_reason and latency_ms to agent_investigations

Revision ID: f1a0e0475704
Revises: c12b8cf23e77
Create Date: 2026-08-14 10:48:55.826485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1a0e0475704'
down_revision: Union[str, Sequence[str], None] = 'c12b8cf23e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Existing rows predate these columns -- backfill with a default, then drop the
    # server default so the application (which always sets both explicitly) is the
    # sole source of truth for new rows going forward.
    op.add_column(
        'agent_investigations',
        sa.Column('termination_reason', sa.String(), nullable=False, server_default='completed'),
    )
    op.add_column(
        'agent_investigations',
        sa.Column('latency_ms', sa.Integer(), nullable=False, server_default='0'),
    )
    op.alter_column('agent_investigations', 'termination_reason', server_default=None)
    op.alter_column('agent_investigations', 'latency_ms', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_investigations', 'latency_ms')
    op.drop_column('agent_investigations', 'termination_reason')
    # ### end Alembic commands ###
